/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.CadastroDAO;
import DAO.FornecedorDAO;
import classes.Cadastro;
import classes.ClassesFornecedor;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class Fornecedor extends javax.swing.JFrame {

    /**
     * Creates new form Fornecedor
     */
    public Fornecedor() {
        initComponents();
    }

    private ClassesFornecedor Fornecedor() {

        ClassesFornecedor fornecedor = new ClassesFornecedor();
        fornecedor.setCod_fornecedor(txtCodigoF.getText());
        fornecedor.setNome_fornecedor(txtNomeF.getText());

        return fornecedor;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomeF = new javax.swing.JTextField();
        btnInserir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(370, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Cadastro Fornecedor");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 30, 270, 40);

        jLabel2.setText("Codigo do fornecedor :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 100, 120, 30);
        getContentPane().add(txtCodigoF);
        txtCodigoF.setBounds(30, 130, 290, 50);

        jLabel3.setText("Nome do fornecedor :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 210, 170, 30);
        getContentPane().add(txtNomeF);
        txtNomeF.setBounds(30, 240, 290, 50);

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        getContentPane().add(btnInserir);
        btnInserir.setBounds(30, 320, 110, 50);

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar);
        btnPesquisar.setBounds(210, 320, 110, 50);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(30, 403, 110, 50);

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletar);
        btnDeletar.setBounds(210, 403, 110, 50);

        jMenuBar1.setName(""); // NOI18N

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        if (txtCodigoF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Código do fornecedor nao"
                    + "pode ficar vazio!");
        } else if (txtNomeF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, preencha o campo "
                    + "nome!");
        } else {
            ClassesFornecedor Fornecedor = Fornecedor();
            String resp = new FornecedorDAO().gravarFornecedor(Fornecedor());
            if (resp.equals("OK")) {
                JOptionPane.showMessageDialog(null, "Registro inserido com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, resp);
            }}
            // TODO add your handling code here:
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
                String resp =  new FornecedorDAO().excluirpecaFornecedor(Fornecedor());
           
           if(resp.equals("OK")){
               
               JOptionPane.showMessageDialog(null, "Exclusão efetuada com sucesso");
           }
           else{
               
               JOptionPane.showMessageDialog(null, resp);
               
               
           }             // TODO add your handling code here:
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        String resp =  new FornecedorDAO().AlterarpecaFornecedor(Fornecedor());
           
           if(resp.equals("OK")){
               
               JOptionPane.showMessageDialog(null, "Alteração efetuada com sucesso");
           }
           else{
               
               JOptionPane.showMessageDialog(null, resp);
               
               
           }     
            
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
              if (txtCodigoF.getText().equals("")) {
           JOptionPane.showMessageDialog(null, "Preencha o código do fornecedor");
        } else {
            ClassesFornecedor fornecedor = new FornecedorDAO().PesquisaFornecedor(txtCodigoF.getText());
            if (fornecedor == null) {
                txtNomeF.setText("");
                JOptionPane.showMessageDialog(null, "forncecedor nao eoncontrado");
            } else {
                txtNomeF.setText(fornecedor.getNome_fornecedor());
                JOptionPane.showMessageDialog(null, "Fornecedor encontrado.");
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField txtCodigoF;
    private javax.swing.JTextField txtNomeF;
    // End of variables declaration//GEN-END:variables

}
