/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.CadastroDAO;
import classes.Cadastro;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author win
 */
public class InformacoesBanco extends javax.swing.JFrame {

    /**
     * Creates new form InformacoesBanco
     */
    public InformacoesBanco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPecas = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        btnCarregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBanco = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tblPecas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de serie", "Codigo do fornecedor", "Nome", "Preço ", "Detalhes tecnicos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPecas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 50, 730, 260);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(20, 460, 260, 40);

        btnCarregar.setText("Limpa");
        btnCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarregar);
        btnCarregar.setBounds(20, 320, 260, 40);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Estoque de peças");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 10, 280, 40);

        btnBanco.setText("Placa de video");
        btnBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBancoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBanco);
        btnBanco.setBounds(280, 320, 220, 40);

        jButton1.setText("Placa mãe");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(500, 320, 250, 40);

        jButton2.setText("Processador");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 360, 260, 40);

        jButton3.setText("Memoria ram");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(280, 360, 220, 40);

        jButton4.setText("Fonte");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(500, 360, 250, 40);

        jButton5.setText("Mouse");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(20, 400, 260, 40);

        jButton6.setText("Teclado");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(280, 400, 220, 40);

        jButton7.setText("Monitor");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(500, 400, 250, 40);

        jMenu1.setText("Ferramentas");

        jMenuItem1.setText("Cadastro");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Consulta");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opções");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Sair");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(790, 571));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarActionPerformed
        String titulos[] = {"NUM_SERIE", "COD_FORNECEDOR", "NM_NOME", "PC_PRECO", "DA_TEC"};
        Object dados[][] = {
            {}};

        DefaultTableModel modelo
                = new DefaultTableModel(dados, titulos);
        tblPecas.setModel(modelo);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarregarActionPerformed

    private void btnBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBancoActionPerformed
        ArrayList<Cadastro> lista = new CadastroDAO().listaPlacaVideo();
        DefaultTableModel modelo = (DefaultTableModel) tblPecas.getModel();
        for (int i = 0; i < lista.size(); i++) {
            modelo.addRow(new String[]{lista.get(i).getSerie(),
                lista.get(i).getCod_Fornecedor(), lista.get(i).getNome(), lista.get(i).getPreco(),
                lista.get(i).getPreco(), lista.get(i).getDados_tec()});
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnBancoActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        ArrayList<Cadastro> lista = new CadastroDAO().listaMonitor();
        DefaultTableModel modelo = (DefaultTableModel) tblPecas.getModel();
        for (int i = 0; i < lista.size(); i++) {
            modelo.addRow(new String[]{lista.get(i).getSerie(),
                lista.get(i).getCod_Fornecedor(), lista.get(i).getNome(), lista.get(i).getPreco(),
                lista.get(i).getPreco(), lista.get(i).getDados_tec()});
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<Cadastro> lista = new CadastroDAO().listaPecas();
        DefaultTableModel modelo = (DefaultTableModel) tblPecas.getModel();
        for (int i = 0; i < lista.size(); i++) {
            modelo.addRow(new String[]{lista.get(i).getSerie(),
                lista.get(i).getCod_Fornecedor(), lista.get(i).getNome(), lista.get(i).getPreco(),
                lista.get(i).getPreco(), lista.get(i).getDados_tec()});
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ArrayList<Cadastro> lista = new CadastroDAO().listaProcessador();
        DefaultTableModel modelo = (DefaultTableModel) tblPecas.getModel();
        for (int i = 0; i < lista.size(); i++) {
            modelo.addRow(new String[]{lista.get(i).getSerie(),
                lista.get(i).getCod_Fornecedor(), lista.get(i).getNome(), lista.get(i).getPreco(),
                lista.get(i).getPreco(), lista.get(i).getDados_tec()});
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ArrayList<Cadastro> lista = new CadastroDAO().listaMouse();
        DefaultTableModel modelo = (DefaultTableModel) tblPecas.getModel();
        for (int i = 0; i < lista.size(); i++) {
            modelo.addRow(new String[]{lista.get(i).getSerie(),
                lista.get(i).getCod_Fornecedor(), lista.get(i).getNome(), lista.get(i).getPreco(),
                lista.get(i).getPreco(), lista.get(i).getDados_tec()});
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ArrayList<Cadastro> lista = new CadastroDAO().listaPecas();
        DefaultTableModel modelo = (DefaultTableModel) tblPecas.getModel();
        for (int i = 0; i < lista.size(); i++) {
            modelo.addRow(new String[]{lista.get(i).getSerie(),
                lista.get(i).getCod_Fornecedor(), lista.get(i).getNome(), lista.get(i).getPreco(),
                lista.get(i).getPreco(), lista.get(i).getDados_tec()});
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ArrayList<Cadastro> lista = new CadastroDAO().listaPecas();
        DefaultTableModel modelo = (DefaultTableModel) tblPecas.getModel();
        for (int i = 0; i < lista.size(); i++) {
            modelo.addRow(new String[]{lista.get(i).getSerie(),
                lista.get(i).getCod_Fornecedor(), lista.get(i).getNome(), lista.get(i).getPreco(),
                lista.get(i).getPreco(), lista.get(i).getDados_tec()});
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        ArrayList<Cadastro> lista = new CadastroDAO().listaTeclado();
        DefaultTableModel modelo = (DefaultTableModel) tblPecas.getModel();
        for (int i = 0; i < lista.size(); i++) {
            modelo.addRow(new String[]{lista.get(i).getSerie(),
                lista.get(i).getCod_Fornecedor(), lista.get(i).getNome(), lista.get(i).getPreco(),
                lista.get(i).getPreco(), lista.get(i).getDados_tec()});
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacoesBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacoesBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacoesBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacoesBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacoesBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanco;
    private javax.swing.JButton btnCarregar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPecas;
    // End of variables declaration//GEN-END:variables
}
