/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.CadastroDAO;
import classes.Cadastro;
import javax.swing.JOptionPane;

/**
 *
 * @author win
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TelaCadastro() {
        initComponents();
    }

    private Cadastro montaComputador() {

        Cadastro cadastro = new Cadastro();
        cadastro.setSerie(txtSerie.getText());
        cadastro.setCod_Fornecedor(txtFornecedor.getText());
        cadastro.setNome(txtNome.getText());
        cadastro.setPreco(txtPreco.getText());
        cadastro.setDados_tec(txtDetalhes.getText());

        return cadastro;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        txtSerie = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        txtDetalhes = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtFornecedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        txtSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerieActionPerformed(evt);
            }
        });
        jPanel1.add(txtSerie);
        txtSerie.setBounds(30, 50, 250, 40);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setText("Serie :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 30, 40, 14);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText("Nome:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 200, 60, 14);

        jLabel4.setText("Detalhes tecnicos:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 350, 130, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setText("             Cadastro");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(230, 10, 420, 40);

        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Placa mãe", "Placa de video", "Processador", "Memoria ram", "Fonte", "Gabinete", "Mouse", "Teclado", "Monitor", "Fornecedor" }));
        jPanel1.add(cbxCategoria);
        cbxCategoria.setBounds(370, 50, 140, 40);

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        jPanel1.add(btnInserir);
        btnInserir.setBounds(580, 40, 180, 50);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlterar);
        btnAlterar.setBounds(580, 220, 180, 50);

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeletar);
        btnDeletar.setBounds(580, 160, 180, 50);

        jLabel6.setText("Categoria:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(310, 60, 60, 20);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar);
        btnVoltar.setBounds(580, 280, 180, 50);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel7.setText("Preço:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 270, 40, 14);

        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });
        jPanel1.add(txtPreco);
        txtPreco.setBounds(30, 290, 250, 40);

        txtDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDetalhesActionPerformed(evt);
            }
        });
        jPanel1.add(txtDetalhes);
        txtDetalhes.setBounds(30, 370, 250, 40);
        jPanel1.add(txtNome);
        txtNome.setBounds(30, 220, 250, 40);
        jPanel1.add(txtFornecedor);
        txtFornecedor.setBounds(30, 140, 250, 40);

        jLabel2.setText("Codigo do fornecedor :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 114, 150, 20);

        txtPesquisar.setText("Pesquisar");
        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(txtPesquisar);
        txtPesquisar.setBounds(580, 100, 180, 50);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Placa mãe", "Placa de video", "Processador", "Memoria Ram", "Fonte", "Gabinete", "Mouse", "Teclado", "Monitor", "Fornecedor", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(360, 110, 150, 130);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 473);

        jMenu1.setText("Ferramentas");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Inserir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Alterar");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Deleta");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opções");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Sair");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(816, 512));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed

        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerieActionPerformed

    private void txtDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDetalhesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDetalhesActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed

        switch (cbxCategoria.getSelectedIndex()) {
            case 0:
                if (cbxCategoria.getSelectedItem().equals("Placa mãe")) {
                    if (txtSerie.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "O Numero de Série não pode"
                                + "ficar vazio!");
                    } else if (txtFornecedor.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "O Numero do fornecedor não pode"
                                + "ficar vazio!");
                    } else if (txtNome.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, preencha o campo "
                                + "nome!");
                    } else if (txtPreco.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, Preencha o preço do produto!");

                    } else if (txtDetalhes.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, preeecha o "
                                + "preço do produto!");
                    } else {
                        Cadastro cadastro = montaComputador();
                        String resp = new CadastroDAO().gravarpeca(montaComputador());
                        if (resp.equals("OK")) {
                            JOptionPane.showMessageDialog(null, "Inserido com sucesso.");
                        } else {
                            JOptionPane.showMessageDialog(null, resp);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor,selecione a categoria.");

                }
                break;

            case 1:
                if (cbxCategoria.getSelectedItem().equals("Placa de video")) {
                    if (txtSerie.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "O Numero de Série não pode"
                                + "ficar vazio!");
                    } else if (txtFornecedor.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "O Numero do fornecedor não pode"
                                + "ficar vazio!");
                    } else if (txtNome.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, preencha o campo "
                                + "nome!");
                    } else if (txtPreco.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, Preencha o preço do produto!");

                    } else if (txtDetalhes.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, preeecha o "
                                + "preço do produto!");
                    } else {
                        Cadastro cadastro = montaComputador();
                        String resp = new CadastroDAO().gravarVideo(montaComputador());
                        if (resp.equals("OK")) {
                            JOptionPane.showMessageDialog(null, "Inserido com sucesso.");
                        } else {
                            JOptionPane.showMessageDialog(null, resp);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor,selecione a categoria.");
                }
                break;
            case 2:
                if (cbxCategoria.getSelectedItem().equals("Processador")) {
                    if (txtSerie.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "O Numero de Série não pode"
                                + "ficar vazio!");
                    } else if (txtFornecedor.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "O Numero do fornecedor não pode"
                                + "ficar vazio!");
                    } else if (txtNome.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, preencha o campo "
                                + "nome!");
                    } else if (txtPreco.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, Preencha o preço do produto!");

                    } else if (txtDetalhes.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, preeecha o "
                                + "preço do produto!");
                    } else {
                        Cadastro cadastro = montaComputador();
                        String resp = new CadastroDAO().gravarprocessador(montaComputador());
                        if (resp.equals("OK")) {
                            JOptionPane.showMessageDialog(null, "Inserido com sucesso.");
                        } else {
                            JOptionPane.showMessageDialog(null, resp);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor,selecione a categoria.");

                }

                break;
            case 3:
                if (cbxCategoria.getSelectedItem().equals("Memoria ram")) {
                    if (txtSerie.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "O Numero de Série não pode"
                                + "ficar vazio!");
                    } else if (txtFornecedor.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "O Numero do fornecedor não pode"
                                + "ficar vazio!");
                    } else if (txtNome.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, preencha o campo "
                                + "nome!");
                    } else if (txtPreco.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, Preencha o preço do produto!");

                    } else if (txtDetalhes.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, preeecha o "
                                + "preço do produto!");
                    } else {
                        Cadastro cadastro = montaComputador();
                        String resp = new CadastroDAO().gravarMemoriaRam(montaComputador());
                        if (resp.equals("OK")) {
                            JOptionPane.showMessageDialog(null, "Inserido com sucesso.");
                        } else {
                            JOptionPane.showMessageDialog(null, resp);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor,selecione a categoria.");

                }

                break;

            case 4:

                if (cbxCategoria.getSelectedItem().equals("Fonte")) {
                    if (txtSerie.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "O Numero de Série não pode"
                                + "ficar vazio!");
                    } else if (txtFornecedor.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "O Numero do fornecedor não pode"
                                + "ficar vazio!");
                    } else if (txtNome.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, preencha o campo "
                                + "nome!");
                    } else if (txtPreco.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, Preencha o preço do produto!");

                    } else if (txtDetalhes.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, preeecha o "
                                + "preço do produto!");
                    } else {
                        Cadastro cadastro = montaComputador();
                        String resp = new CadastroDAO().gravarFonte(montaComputador());
                        if (resp.equals("OK")) {
                            JOptionPane.showMessageDialog(null, "Inserido com sucesso.");
                        } else {
                            JOptionPane.showMessageDialog(null, resp);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor,selecione a categoria.");

                }

                break;

            case 5:

                if (cbxCategoria.getSelectedItem().equals("Gabinete")) {
                    if (txtSerie.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "O Numero de Série não pode"
                                + "ficar vazio!");
                    } else if (txtFornecedor.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "O Numero do fornecedor não pode"
                                + "ficar vazio!");
                    } else if (txtNome.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, preencha o campo "
                                + "nome!");
                    } else if (txtPreco.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, Preencha o preço do produto!");

                    } else if (txtDetalhes.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, preeecha o "
                                + "preço do produto!");
                    } else {
                        Cadastro cadastro = montaComputador();
                        String resp = new CadastroDAO().gravarGabinete(montaComputador());
                        if (resp.equals("OK")) {
                            JOptionPane.showMessageDialog(null, "Inserido com sucesso.");
                        } else {
                            JOptionPane.showMessageDialog(null, resp);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor,selecione a categoria.");

                }

                break;

            case 6:

                if (cbxCategoria.getSelectedItem().equals("Mouse")) {
                    if (txtSerie.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "O Numero de Série não pode"
                                + "ficar vazio!");
                    } else if (txtFornecedor.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "O Numero do fornecedor não pode"
                                + "ficar vazio!");
                    } else if (txtNome.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, preencha o campo "
                                + "nome!");
                    } else if (txtPreco.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, Preencha o preço do produto!");

                    } else if (txtDetalhes.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, preeecha o "
                                + "preço do produto!");
                    } else {
                        Cadastro cadastro = montaComputador();
                        String resp = new CadastroDAO().gravarMouse(montaComputador());
                        if (resp.equals("OK")) {
                            JOptionPane.showMessageDialog(null, "Inserido com sucesso.");
                        } else {
                            JOptionPane.showMessageDialog(null, resp);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor,selecione a categoria.");

                }

                break;

            case 7:

                if (cbxCategoria.getSelectedItem().equals("Teclado")) {
                    if (txtSerie.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "O Numero de Série não pode"
                                + "ficar vazio!");
                    } else if (txtFornecedor.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "O Numero do fornecedor não pode"
                                + "ficar vazio!");
                    } else if (txtNome.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, preencha o campo "
                                + "nome!");
                    } else if (txtPreco.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, Preencha o preço do produto!");

                    } else if (txtDetalhes.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, preeecha o "
                                + "preço do produto!");
                    } else {
                        Cadastro cadastro = montaComputador();
                        String resp = new CadastroDAO().gravarTeclado(montaComputador());
                        if (resp.equals("OK")) {
                            JOptionPane.showMessageDialog(null, "Inserido com sucesso.");
                        } else {
                            JOptionPane.showMessageDialog(null, resp);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor,selecione a categoria.");

                }

                break;

            case 8:
                if (cbxCategoria.getSelectedItem().equals("Monitor")) {
                    if (txtSerie.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "O Numero de Série não pode"
                                + "ficar vazio!");
                    } else if (txtFornecedor.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "O Numero do fornecedor não pode"
                                + "ficar vazio!");
                    } else if (txtNome.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, preencha o campo "
                                + "nome!");
                    } else if (txtPreco.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, Preencha o preço do produto!");

                    } else if (txtDetalhes.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Por favor, preeecha o "
                                + "preço do produto!");
                    } else {
                        Cadastro cadastro = montaComputador();
                        String resp = new CadastroDAO().gravarMonitor(montaComputador());
                        if (resp.equals("OK")) {
                            JOptionPane.showMessageDialog(null, "Inserido com sucesso.");
                        } else {
                            JOptionPane.showMessageDialog(null, resp);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor,selecione a categoria.");

                }

                break;
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnInserirActionPerformed

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        switch (cbxCategoria.getSelectedIndex()) {

            case 0:

                if (txtSerie.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "preencha o numero de Serie");
                } else {
                    Cadastro cadastro = new CadastroDAO().buscaPlacaMae(txtSerie.getText());
                    if (cadastro == null) {
                        txtFornecedor.setText("");
                        txtNome.setText("");
                        txtPreco.setText("");
                        txtDetalhes.setText("");
                        JOptionPane.showMessageDialog(null, "nao cadastrado ");
                    } else {
                        txtFornecedor.setText(cadastro.getCod_Fornecedor());
                        txtNome.setText(cadastro.getNome());
                        txtPreco.setText(cadastro.getPreco());
                        txtDetalhes.setText(cadastro.getDados_tec());
                    }
                }

                break;
            case 1:

                if (txtSerie.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "preencha o numero de Serie");
                } else {
                    Cadastro cadastro = new CadastroDAO().buscaPlacaDeVideo(txtSerie.getText());
                    if (cadastro == null) {
                        txtFornecedor.setText("");
                        txtNome.setText("");
                        txtPreco.setText("");
                        txtDetalhes.setText("");
                        JOptionPane.showMessageDialog(null, "nao cadastrado ");
                    } else {
                        txtFornecedor.setText(cadastro.getCod_Fornecedor());
                        txtNome.setText(cadastro.getNome());
                        txtPreco.setText(cadastro.getPreco());
                        txtDetalhes.setText(cadastro.getDados_tec());
                    }
                }

                break;

            case 2:

                if (txtSerie.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "preencha o numero de Serie");
                } else {
                    Cadastro cadastro = new CadastroDAO().buscaProcessador(txtSerie.getText());
                    if (cadastro == null) {
                        txtFornecedor.setText("");
                        txtNome.setText("");
                        txtPreco.setText("");
                        txtDetalhes.setText("");
                        JOptionPane.showMessageDialog(null, "nao cadastrado ");
                    } else {
                        txtFornecedor.setText(cadastro.getCod_Fornecedor());
                        txtNome.setText(cadastro.getNome());
                        txtPreco.setText(cadastro.getPreco());
                        txtDetalhes.setText(cadastro.getDados_tec());
                    }
                }

                break;

            case 3:

                if (txtSerie.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "preencha o numero de Serie");
                } else {
                    Cadastro cadastro = new CadastroDAO().buscaMemoriaRam(txtSerie.getText());
                    if (cadastro == null) {
                        txtFornecedor.setText("");
                        txtNome.setText("");
                        txtPreco.setText("");
                        txtDetalhes.setText("");
                        JOptionPane.showMessageDialog(null, "nao cadastrado ");
                    } else {
                        txtFornecedor.setText(cadastro.getCod_Fornecedor());
                        txtNome.setText(cadastro.getNome());
                        txtPreco.setText(cadastro.getPreco());
                        txtDetalhes.setText(cadastro.getDados_tec());
                    }
                }

                break;
            case 4:

                if (txtSerie.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "preencha o numero de Serie");
                } else {
                    Cadastro cadastro = new CadastroDAO().buscaFonte(txtSerie.getText());
                    if (cadastro == null) {
                        txtFornecedor.setText("");
                        txtNome.setText("");
                        txtPreco.setText("");
                        txtDetalhes.setText("");
                        JOptionPane.showMessageDialog(null, "nao cadastrado ");
                    } else {
                        txtFornecedor.setText(cadastro.getCod_Fornecedor());
                        txtNome.setText(cadastro.getNome());
                        txtPreco.setText(cadastro.getPreco());
                        txtDetalhes.setText(cadastro.getDados_tec());
                    }
                }

                break;
            case 5:

                if (txtSerie.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "preencha o numero de Serie");
                } else {
                    Cadastro cadastro = new CadastroDAO().buscaGabinete(txtSerie.getText());
                    if (cadastro == null) {
                        txtFornecedor.setText("");
                        txtNome.setText("");
                        txtPreco.setText("");
                        txtDetalhes.setText("");
                        JOptionPane.showMessageDialog(null, "nao cadastrado ");
                    } else {
                        txtFornecedor.setText(cadastro.getCod_Fornecedor());
                        txtNome.setText(cadastro.getNome());
                        txtPreco.setText(cadastro.getPreco());
                        txtDetalhes.setText(cadastro.getDados_tec());
                    }
                }

                break;
            case 6:

                if (txtSerie.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "preencha o numero de Serie");
                } else {
                    Cadastro cadastro = new CadastroDAO().buscaMouse(txtSerie.getText());
                    if (cadastro == null) {
                        txtFornecedor.setText("");
                        txtNome.setText("");
                        txtPreco.setText("");
                        txtDetalhes.setText("");
                        JOptionPane.showMessageDialog(null, "nao cadastrado ");
                    } else {
                        txtFornecedor.setText(cadastro.getCod_Fornecedor());
                        txtNome.setText(cadastro.getNome());
                        txtPreco.setText(cadastro.getPreco());
                        txtDetalhes.setText(cadastro.getDados_tec());
                    }
                }

                break;
            case 7:

                if (txtSerie.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "preencha o numero de Serie");
                } else {
                    Cadastro cadastro = new CadastroDAO().buscaTeclado(txtSerie.getText());
                    if (cadastro == null) {
                        txtFornecedor.setText("");
                        txtNome.setText("");
                        txtPreco.setText("");
                        txtDetalhes.setText("");
                        JOptionPane.showMessageDialog(null, "nao cadastrado ");
                    } else {
                        txtFornecedor.setText(cadastro.getCod_Fornecedor());
                        txtNome.setText(cadastro.getNome());
                        txtPreco.setText(cadastro.getPreco());
                        txtDetalhes.setText(cadastro.getDados_tec());
                    }
                }

                break;
            case 8:

                if (txtSerie.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "preencha o numero de Serie");
                } else {
                    Cadastro cadastro = new CadastroDAO().buscaMonitor(txtSerie.getText());
                    if (cadastro == null) {
                        txtFornecedor.setText("");
                        txtNome.setText("");
                        txtPreco.setText("");
                        txtDetalhes.setText("");
                        JOptionPane.showMessageDialog(null, "nao cadastrado ");
                    } else {
                        txtFornecedor.setText(cadastro.getCod_Fornecedor());
                        txtNome.setText(cadastro.getNome());
                        txtPreco.setText(cadastro.getPreco());
                        txtDetalhes.setText(cadastro.getDados_tec());
                    }
                }

                break;
            case 9:

                break;
        }

// TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed

        switch (cbxCategoria.getSelectedIndex()) {

            case 0:

                if (cbxCategoria.getSelectedItem().equals("Placa mãe")) {

                    Cadastro cadastro = montaComputador();
                    String resp = new CadastroDAO().excluirPlacaMae(montaComputador());

                    if (resp.equals("OK")) {

                        JOptionPane.showMessageDialog(null, "Exclusão efetuada com sucesso");
                    } else {

                        JOptionPane.showMessageDialog(null, resp);

                    }

                }

                break;
            case 1:

                if (cbxCategoria.getSelectedItem().equals("Placa de video")) {

                    Cadastro cadastro = montaComputador();
                    String resp = new CadastroDAO().excluirplacadevideo(montaComputador());

                    if (resp.equals("OK")) {

                        JOptionPane.showMessageDialog(null, "Exclusão efetuada com sucesso");
                    } else {

                        JOptionPane.showMessageDialog(null, resp);

                    }

                }

                break;

            case 2:

                if (cbxCategoria.getSelectedItem().equals("Processador")) {

                    Cadastro cadastro = montaComputador();
                    String resp = new CadastroDAO().excluiprocessadore(montaComputador());

                    if (resp.equals("OK")) {

                        JOptionPane.showMessageDialog(null, "Exclusão efetuada com sucesso");
                    } else {

                        JOptionPane.showMessageDialog(null, resp);

                    }

                }

                break;

            case 3:

                if (cbxCategoria.getSelectedItem().equals("Memoria ram")) {

                    Cadastro cadastro = montaComputador();
                    String resp = new CadastroDAO().excluimemoriaRam(montaComputador());

                    if (resp.equals("OK")) {

                        JOptionPane.showMessageDialog(null, "Exclusão efetuada com sucesso");
                    } else {

                        JOptionPane.showMessageDialog(null, resp);

                    }

                }

                break;
            case 4:

                if (cbxCategoria.getSelectedItem().equals("Fonte")) {

                    Cadastro cadastro = montaComputador();
                    String resp = new CadastroDAO().excluirfonte(montaComputador());

                    if (resp.equals("OK")) {

                        JOptionPane.showMessageDialog(null, "Exclusão efetuada com sucesso");
                    } else {

                        JOptionPane.showMessageDialog(null, resp);

                    }

                }

                break;
            case 5:

                if (cbxCategoria.getSelectedItem().equals("Gabinete")) {

                    Cadastro cadastro = montaComputador();
                    String resp = new CadastroDAO().excluirgabinete(montaComputador());

                    if (resp.equals("OK")) {

                        JOptionPane.showMessageDialog(null, "Exclusão efetuada com sucesso");
                    } else {

                        JOptionPane.showMessageDialog(null, resp);

                    }

                }

                break;
            case 6:

                if (cbxCategoria.getSelectedItem().equals("Mouse")) {

                    Cadastro cadastro = montaComputador();
                    String resp = new CadastroDAO().excluirmouse(montaComputador());

                    if (resp.equals("OK")) {

                        JOptionPane.showMessageDialog(null, "Exclusão efetuada com sucesso");
                    } else {

                        JOptionPane.showMessageDialog(null, resp);

                    }

                }

                break;
            case 7:

                if (cbxCategoria.getSelectedItem().equals("Teclado")) {

                    Cadastro cadastro = montaComputador();
                    String resp = new CadastroDAO().excluirteclado(montaComputador());

                    if (resp.equals("OK")) {

                        JOptionPane.showMessageDialog(null, "Exclusão efetuada com sucesso");
                    } else {

                        JOptionPane.showMessageDialog(null, resp);

                    }

                }

                break;
            case 8:

                if (cbxCategoria.getSelectedItem().equals("Monitor")) {

                    Cadastro cadastro = montaComputador();
                    String resp = new CadastroDAO().excluirmonitor(montaComputador());

                    if (resp.equals("OK")) {

                        JOptionPane.showMessageDialog(null, "Exclusão efetuada com sucesso");
                    } else {

                        JOptionPane.showMessageDialog(null, resp);

                    }

                }

                break;
            case 9:

                break;
        }


    }//GEN-LAST:event_btnDeletarActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        switch (cbxCategoria.getSelectedIndex()) {

            case 0:

                if (cbxCategoria.getSelectedItem().equals("Placa mãe")) {

                    Cadastro cadastro = montaComputador();
                    String resp = new CadastroDAO().alteraPlacaMae(montaComputador());

                    if (resp.equals("OK")) {

                        JOptionPane.showMessageDialog(null, "Alteração efetuada com sucesso");
                    } else {

                        JOptionPane.showMessageDialog(null, resp);

                    }

                }

                break;
            case 1:

                if (cbxCategoria.getSelectedItem().equals("Placa de video")) {

                    Cadastro cadastro = montaComputador();
                    String resp = new CadastroDAO().alteraPlacaDeVideo(montaComputador());

                    if (resp.equals("OK")) {

                        JOptionPane.showMessageDialog(null, "Alteração efetuada com sucesso");
                    } else {

                        JOptionPane.showMessageDialog(null, resp);

                    }

                }

                break;

            case 2:

                if (cbxCategoria.getSelectedItem().equals("Processador")) {

                    Cadastro cadastro = montaComputador();
                    String resp = new CadastroDAO().alteraProcessador(montaComputador());

                    if (resp.equals("OK")) {

                        JOptionPane.showMessageDialog(null, "Alteração efetuada com sucesso");
                    } else {

                        JOptionPane.showMessageDialog(null, resp);

                    }

                }

                break;

            case 3:

                if (cbxCategoria.getSelectedItem().equals("Memoria ram")) {

                    Cadastro cadastro = montaComputador();
                    String resp = new CadastroDAO().alteraMemoriaRam(montaComputador());

                    if (resp.equals("OK")) {

                        JOptionPane.showMessageDialog(null, "Alteração efetuada com sucesso");
                    } else {

                        JOptionPane.showMessageDialog(null, resp);

                    }

                }

                break;
            case 4:

                if (cbxCategoria.getSelectedItem().equals("Fonte")) {

                    Cadastro cadastro = montaComputador();
                    String resp = new CadastroDAO().alteraFonte(montaComputador());

                    if (resp.equals("OK")) {

                        JOptionPane.showMessageDialog(null, "Alteração efetuada com sucesso");
                    } else {

                        JOptionPane.showMessageDialog(null, resp);

                    }

                }

                break;
            case 5:

                if (cbxCategoria.getSelectedItem().equals("Gabinete")) {

                    Cadastro cadastro = montaComputador();
                    String resp = new CadastroDAO().alteraGabinete(montaComputador());

                    if (resp.equals("OK")) {

                        JOptionPane.showMessageDialog(null, "Alteração efetuada com sucesso");
                    } else {

                        JOptionPane.showMessageDialog(null, resp);

                    }

                }

                break;
            case 6:

                if (cbxCategoria.getSelectedItem().equals("Mouse")) {

                    Cadastro cadastro = montaComputador();
                    String resp = new CadastroDAO().alteraMouse(montaComputador());

                    if (resp.equals("OK")) {

                        JOptionPane.showMessageDialog(null, "Alteração efetuada com sucesso");
                    } else {

                        JOptionPane.showMessageDialog(null, resp);

                    }

                }

                break;
            case 7:

                if (cbxCategoria.getSelectedItem().equals("Teclado")) {

                    Cadastro cadastro = montaComputador();
                    String resp = new CadastroDAO().alteraTeclado(montaComputador());

                    if (resp.equals("OK")) {

                        JOptionPane.showMessageDialog(null, "Alteração efetuada com sucesso");
                    } else {

                        JOptionPane.showMessageDialog(null, resp);

                    }

                }

                break;
            case 8:

                if (cbxCategoria.getSelectedItem().equals("Monitor")) {

                    Cadastro cadastro = montaComputador();
                    String resp = new CadastroDAO().alteraMonitor(montaComputador());

                    if (resp.equals("OK")) {

                        JOptionPane.showMessageDialog(null, "Alteração efetuada com sucesso");
                    } else {

                        JOptionPane.showMessageDialog(null, resp);

                    }

                }

                break;
            case 9:

                break;
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox cbxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtDetalhes;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtNome;
    private javax.swing.JButton txtPesquisar;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtSerie;
    // End of variables declaration//GEN-END:variables

    private Object CadastroDAO() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
